# 5G-Energy consumption
#### Supervised Learning Regression

## Project Overview
The goal of the project is to build and train a machine learning model to estimate the energy consumption of different 5G base stations. This involves analyzing various factors such as:

 *** Instructions

    Import you data and perform basic data exploration phase
        Display general information about the dataset
        Create a pandas profiling reports to gain insights into the dataset
        Handle Missing and corrupted values
        Remove duplicates, if they exist
        Handle outliers, if they exist
        Encode categorical features
    Select your target variable and the features
    Split your dataset to training and test sets
    Based on your data exploration phase select a ML regression algorithm and train it on the training set
    Assess your model performance on the test set using relevant evaluation metrics
    Discuss with your cohort alternative ways to improve your model performance

## Dataset
- **Source:** ITU (5G-Energy consumption)
`

## Methodology

1. Data Understanding and Exploration


    Dataset Acquisition: Obtain the '5G-Energy consumption' dataset.

    Initial Exploration: Use descriptive statistics and visualizations to understand the dataset's structure, features, and basic characteristics.

    Pandas Profiling: Generate a profiling report to gain deeper insights into distributions, correlations, and potential issues.


2. Data Preprocessing


    Handling Missing Values: Identify and address missing or corrupted data through imputation or removal.

    Removing Duplicates: Check for and eliminate any duplicate records to ensure data integrity.

    Outlier Detection and Treatment: Identify outliers using statistical methods (like Z-score or IQR) and decide whether to remove or    adjust them.

    Categorical Encoding: Convert categorical variables into numerical format using techniques like one-hot encoding.



3. **Visualizations:**
   - Scatter Plots: Plotting predicted vs. actual values helps visualize model performance.

## Results & Interpretation
  1. **Model Performance Metrics**
  2. **Feature Importance**


## Conclusion
The analysis and modeling of the '5G-Energy consumption' dataset provide valuable insights into factors influencing energy use in telecommunications. The model demonstrates strong predictive capabilities, which can inform strategic decisions aimed at reducing operational costs and enhancing energy efficiency. 

## Technologies Used
- Python (Pandas, NumPy, Scikit-Learn, Matplotlib, Seaborn)

- StudentName: Olalekan P Elebute

In [120]:
##importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import ydata_profiling

In [122]:
# Loading Data Set Using Pandas|
Energy_Data = pd.read_csv(r"C:\Users\MAC\5G_energy_consumption_dataset.csv")

In [124]:
Energy_Data.head()

              Time   BS     Energy      load  ESMODE   TXpower
0  20230101 010000  B_0  64.275037  0.487936     0.0  7.101719
1  20230101 020000  B_0  55.904335  0.344468     0.0  7.101719
2  20230101 030000  B_0  57.698057  0.193766     0.0  7.101719
3  20230101 040000  B_0  55.156951  0.222383     0.0  7.101719
4  20230101 050000  B_0  56.053812  0.175436     0.0  7.101719

In [126]:
Energy_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92629 entries, 0 to 92628
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Time     92629 non-null  object
 1   BS       92629 non-null  object
 2   Energy   92629 non-null  float64
 3   load     92629 non-null  float64
 4   ESMODE   92629 non-null  float64
 5   TXpower  92629 non-null  float64
dtypes: float64(4), object(2)
memory usage: 4.2+ MB

In [128]:
Energy_Data.describe()

             Energy          load        ESMODE       TXpower
count  92629.000000  92629.000000  92629.000000  92629.000000
mean      28.138997      0.244705      0.081361      6.765427
std       13.934645      0.234677      0.382317      0.309929
min        0.747384      0.000000      0.000000      5.381166
25%       18.236173      0.057370      0.000000      6.427504
50%       24.065770      0.165550      0.000000      6.875934
75%       35.724963      0.363766      0.000000      6.875934
max      100.000000      0.993957      4.000000      8.375336

In [130]:
Energy_Data.shape

(92629, 6)

In [132]:
Energy_Data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
92624    False
92625    False
92626    False
92627    False
92628    False
Length: 92629, dtype: bool

In [134]:
#Check for columns
Energy_Data.columns

Index(['Time', 'BS', 'Energy', 'load', 'ESMODE', 'TXpower'], dtype='object')

In [136]:
# Checking Null Values
Energy_Data.isnull()

        Time     BS  Energy   load  ESMODE  TXpower
0      False  False   False  False   False    False
1      False  False   False  False   False    False
2      False  False   False  False   False    False
3      False  False   False  False   False    False
4      False  False   False  False   False    False
...      ...    ...     ...    ...     ...      ...
92624  False  False   False  False   False    False
92625  False  False   False  False   False    False
92626  False  False   False  False   False    False
92627  False  False   False  False   False    False
92628  False  False   False  False   False    False

[92629 rows x 6 columns]

In [138]:
Energy_Data.isnull().sum()

Time       0
BS         0
Energy     0
load       0
ESMODE     0
TXpower    0
dtype: int64

In [140]:
print(type(Energy_Data))

<class 'pandas.core.frame.DataFrame'>

In [142]:
from pandas_profiling import ProfileReport

In [144]:
Energy_Data = Energy_Data.apply(pd.to_numeric, errors='coerce')

In [97]:
# Creating a pandas profiling report
Energy_Data = ProfileReport(Energy_Data, title="Pandas Profiling Report", explorative=True)
Energy_Data.to_file("output_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [146]:
# Checking Outliers
#Lets for example use IQR to dect outliers
Q1 = Energy_Data.quantile(0.25, axis=1)
Q3 = Energy_Data.quantile(0.75, axis=1)
IQR = Q3 - Q1

In [156]:
IQR

0        21.029096
1        19.044022
2        19.605479
3        18.948740
4        19.208165
           ...
92624     9.090923
92625     9.094601
92626     8.815969
92627     8.851435
92628     8.784124
Length: 92629, dtype: float64

In [160]:
Energy_Data

       Time  BS     Energy      load  ESMODE   TXpower
0       NaN NaN  64.275037  0.487936     0.0  7.101719
1       NaN NaN  55.904335  0.344468     0.0  7.101719
2       NaN NaN  57.698057  0.193766     0.0  7.101719
3       NaN NaN  55.156951  0.222383     0.0  7.101719
4       NaN NaN  56.053812  0.175436     0.0  7.101719
...     ...  ..        ...       ...     ...       ...
92624   NaN NaN  14.648729  0.087538     0.0  7.325859
92625   NaN NaN  14.648729  0.082635     0.0  7.325859
92626   NaN NaN  13.452915  0.055538     0.0  7.325859
92627   NaN NaN  13.602392  0.058077     0.0  7.325859
92628   NaN NaN  13.303438  0.048173     0.0  7.325859

[92629 rows x 6 columns]

In [162]:
dummies = pd.get_dummies(Energy_Data, drop_first=0.2)
dummies

       Time  BS     Energy      load  ESMODE   TXpower
0       NaN NaN  64.275037  0.487936     0.0  7.101719
1       NaN NaN  55.904335  0.344468     0.0  7.101719
2       NaN NaN  57.698057  0.193766     0.0  7.101719
3       NaN NaN  55.156951  0.222383     0.0  7.101719
4       NaN NaN  56.053812  0.175436     0.0  7.101719
...     ...  ..        ...       ...     ...       ...
92624   NaN NaN  14.648729  0.087538     0.0  7.325859
92625   NaN NaN  14.648729  0.082635     0.0  7.325859
92626   NaN NaN  13.452915  0.055538     0.0  7.325859
92627   NaN NaN  13.602392  0.058077     0.0  7.325859
92628   NaN NaN  13.303438  0.048173     0.0  7.325859

[92629 rows x 6 columns]

In [182]:
merged = pd.concat([Energy_Data, dummies], axis=1)
merged.drop(columns=["Time"], inplace=True)
merged.drop(columns=["BS"], inplace=True)

In [184]:
merged

,Energy,load,ESMODE,TXpower,Energy,load,ESMODE,TXpower
0,64.275037,0.487936,0.0,7.101719,64.275037,0.487936,0.0,7.101719
1,55.904335,0.344468,0.0,7.101719,55.904335,0.344468,0.0,7.101719
2,57.698057,0.193766,0.0,7.101719,57.698057,0.193766,0.0,7.101719
3,55.156951,0.222383,0.0,7.101719,55.156951,0.222383,0.0,7.101719
4,56.053812,0.175436,0.0,7.101719,56.053812,0.175436,0.0,7.101719
...,...,...,...,...,...,...,...,...
92624,14.648729,0.087538,0.0,7.325859,14.648729,0.087538,0.0,7.325859
92625,14.648729,0.082635,0.0,7.325859,14.648729,0.082635,0.0,7.325859
92626,13.452915,0.055538,0.0,7.325859,13.452915,0.055538,0.0,7.325859
92627,13.602392,0.058077,0.0,7.325859,13.602392,0.058077,0.0,7.325859
92628,13.303438,0.048173,0.0,7.325859,13.303438,0.048173,0.0,7.325859

In [186]:
# sorting the independent variable into x
y = merged.Energy
x = merged.drop("Energy", axis=1)

In [188]:
x

           load  ESMODE   TXpower      load  ESMODE   TXpower
0      0.487936     0.0  7.101719  0.487936     0.0  7.101719
1      0.344468     0.0  7.101719  0.344468     0.0  7.101719
2      0.193766     0.0  7.101719  0.193766     0.0  7.101719
3      0.222383     0.0  7.101719  0.222383     0.0  7.101719
4      0.175436     0.0  7.101719  0.175436     0.0  7.101719
...         ...     ...       ...       ...     ...       ...
92624  0.087538     0.0  7.325859  0.087538     0.0  7.325859
92625  0.082635     0.0  7.325859  0.082635     0.0  7.325859
92626  0.055538     0.0  7.325859  0.055538     0.0  7.325859
92627  0.058077     0.0  7.325859  0.058077     0.0  7.325859
92628  0.048173     0.0  7.325859  0.048173     0.0  7.325859

[92629 rows x 6 columns]

In [190]:
#Splitting Dataset into Training and Test Sets
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(74103, 6) (18526, 6) (74103, 2) (18526, 2)

In [194]:
# Import the Linear regression model
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [196]:
model.fit(x, y)

LinearRegression()

In [218]:
#Training a Machine Learning Regression Algorithm
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(x_train, y_train)

RandomForestRegressor(random_state=42)

In [220]:
#Assessing Model Performance Using Relevant Evaluation Metrics
from sklearn.metrics import mean_squared_error, r2_score
y_predict = model.predict(x_test)

MSE = mean_squared_error(y_test, y_predict)
r2 = r2_score(y_test, y_predict)
print(f'Mean Squared Error: {MSE}')
print(f'R² Score: {r2}')

Mean Squared Error: 36.56812060835254
R² Score: 0.8073397417085313

In [224]:
model.score(x,y)

0.9342596574984292